In [18]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [19]:
(x_train, y_train) , (x_test, y_test) = keras.datasets.mnist.load_data()

Normalizing the data and splitting into test train split

In [20]:
x_train = x_train / 255
x_test = x_test / 255

In [21]:
x_train_flattened = x_train.reshape(len(x_train), 28*28)
x_test_flattened = x_test.reshape(len(x_test), 28*28)

NEURAL NETWORK WITH 0 HIDDEN LAYERS

In [33]:
x = np.concatenate((x_train, x_test))
y = np.concatenate((y_train, y_test))

In [34]:
# Split the data into training and testing sets
num_train = int(0.7 * len(x))
x_train, y_train = x[:num_train], y[:num_train]
x_test, y_test = x[num_train:], y[num_train:]

# Reshape the input data to be 2D (samples x features)
x_train_flattened = x_train.reshape(-1, 784)
x_test_flattened = x_test.reshape(-1, 784)


In [22]:
model = keras.Sequential([
    keras.layers.Dense(10, input_shape = (784,),activation = 'softmax')
])

model.compile(optimizer = 'adam' ,
              loss =  'sparse_categorical_crossentropy' ,
              metrics = ['accuracy'])

model.fit(x_train_flattened, y_train, epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4669 - accuracy: 0.8787
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3039 - accuracy: 0.9148
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2834 - accuracy: 0.9212
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2732 - accuracy: 0.9234
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2670 - accuracy: 0.9253


In [23]:
model.evaluate(x_test_flattened, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.2713 - accuracy: 0.9242


[0.27131322026252747, 0.9241999983787537]

In [35]:
y_predicted = model.predict(x_test_flattened)
y_predicted_labels = [np.argmax(i) for i in y_predicted]

657/657 [==============================] - 1s 1ms/step


In [36]:
# confusion_matrix = tf.math.confusion_matrix(labels = y_test,predictions = y_predicted_labels )
# confusion_matrix
num_classes = 10
confusion_matrix = np.zeros((num_classes, num_classes))
for i in range(len(y_test)):
    true_label = y_test[i]
    predicted_label = y_predicted_labels[i]
    confusion_matrix[true_label][predicted_label] += 1

print(confusion_matrix)

[[2.047e+03 0.000e+00 1.000e+00 4.000e+00 2.000e+00 5.000e+00 7.000e+00
  6.000e+00 6.000e+00 0.000e+00]
 [0.000e+00 2.259e+03 6.000e+00 7.000e+00 3.000e+00 4.000e+00 4.000e+00
  3.000e+00 2.000e+01 1.000e+00]
 [1.500e+01 2.000e+01 1.897e+03 4.300e+01 2.500e+01 4.000e+00 1.800e+01
  2.600e+01 6.700e+01 8.000e+00]
 [1.100e+01 1.000e+00 3.000e+01 1.993e+03 3.000e+00 5.000e+01 6.000e+00
  1.200e+01 3.100e+01 1.800e+01]
 [5.000e+00 1.100e+01 4.000e+00 2.000e+00 1.948e+03 0.000e+00 1.000e+01
  5.000e+00 1.200e+01 5.400e+01]
 [2.600e+01 5.000e+00 1.300e+01 8.600e+01 1.900e+01 1.654e+03 3.000e+01
  1.000e+01 4.700e+01 1.700e+01]
 [2.100e+01 5.000e+00 9.000e+00 2.000e+00 2.000e+01 1.900e+01 1.939e+03
  2.000e+00 4.000e+00 0.000e+00]
 [5.000e+00 1.200e+01 2.900e+01 1.500e+01 1.600e+01 1.000e+00 0.000e+00
  2.062e+03 3.000e+00 7.400e+01]
 [2.100e+01 2.800e+01 1.500e+01 6.100e+01 1.300e+01 4.700e+01 1.000e+01
  1.900e+01 1.834e+03 2.600e+01]
 [1.500e+01 1.200e+01 3.000e+00 2.400e+01 6.300e+01 1.2

#1 BASIC NEURAL NETWORK WITH MULTIPLE 2 HIDDEN LAYERS AND SIGMOID FUNCTION

In [37]:
# Split the data into training and testing sets
num_train = int(0.67 * len(x))
x_train, y_train = x[:num_train], y[:num_train]
x_test, y_test = x[num_train:], y[num_train:]

# Reshape the input data to be 2D (samples x features)
x_train_flattened = x_train.reshape(-1, 784)
x_test_flattened = x_test.reshape(-1, 784)


In [40]:
model = keras.Sequential([
    keras.layers.Dense(100, input_shape = (784,),activation = 'sigmoid') ,
    keras.layers.Dense(100, input_shape = (784,),activation = 'sigmoid') ,
    keras.layers.Dense(10 ,activation = 'softmax')

])

model.compile(optimizer = 'adam' ,
              loss =  'sparse_categorical_crossentropy' ,
              metrics = ['accuracy'])

model.fit(x_train_flattened, y_train, epochs = 5)

Epoch 1/5
1466/1466 [==============================] - 5s 3ms/step - loss: 0.5389 - accuracy: 0.8599
Epoch 2/5
1466/1466 [==============================] - 6s 4ms/step - loss: 0.2012 - accuracy: 0.9401
Epoch 3/5
1466/1466 [==============================] - 6s 4ms/step - loss: 0.1435 - accuracy: 0.9572
Epoch 4/5
1466/1466 [==============================] - 4s 3ms/step - loss: 0.1089 - accuracy: 0.9680
Epoch 5/5
1466/1466 [==============================] - 5s 4ms/step - loss: 0.0853 - accuracy: 0.9751


In [11]:
model.evaluate(x_test_flattened, y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.0940 - accuracy: 0.9716


[0.09396137297153473, 0.9715999960899353]

In [38]:
y_predicted1 = model.predict(x_test_flattened)
y_predicted_labels1 = [np.argmax(i) for i in y_predicted1]

722/722 [==============================] - 1s 1ms/step


In [39]:
# confusion_matrix = tf.math.confusion_matrix(labels = y_test,predictions = y_predicted_labels1 )
# confusion_matrix
num_classes = 10
confusion_matrix1 = np.zeros((num_classes, num_classes))
for i in range(len(y_test)):
    true_label1 = y_test[i]
    predicted_label1 = y_predicted_labels1[i]
    confusion_matrix1[true_label1][predicted_label1] += 1

print(confusion_matrix1)


[[2.255e+03 0.000e+00 1.000e+00 5.000e+00 4.000e+00 5.000e+00 7.000e+00
  6.000e+00 7.000e+00 0.000e+00]
 [0.000e+00 2.491e+03 6.000e+00 7.000e+00 3.000e+00 5.000e+00 4.000e+00
  3.000e+00 2.000e+01 3.000e+00]
 [2.200e+01 2.300e+01 2.102e+03 4.600e+01 2.600e+01 4.000e+00 2.100e+01
  2.900e+01 7.200e+01 8.000e+00]
 [1.100e+01 1.000e+00 3.300e+01 2.179e+03 3.000e+00 5.500e+01 9.000e+00
  1.300e+01 3.500e+01 2.000e+01]
 [5.000e+00 1.100e+01 4.000e+00 2.000e+00 2.155e+03 0.000e+00 1.300e+01
  5.000e+00 1.300e+01 6.100e+01]
 [2.800e+01 5.000e+00 1.400e+01 9.600e+01 2.100e+01 1.815e+03 3.300e+01
  1.300e+01 4.900e+01 2.100e+01]
 [2.500e+01 5.000e+00 9.000e+00 3.000e+00 2.200e+01 2.100e+01 2.137e+03
  2.000e+00 5.000e+00 0.000e+00]
 [6.000e+00 1.300e+01 3.100e+01 1.600e+01 1.700e+01 1.000e+00 0.000e+00
  2.260e+03 3.000e+00 7.900e+01]
 [2.600e+01 3.200e+01 1.800e+01 7.100e+01 1.300e+01 5.000e+01 1.100e+01
  2.000e+01 2.019e+03 2.800e+01]
 [1.500e+01 1.300e+01 3.000e+00 2.800e+01 6.500e+01 1.3

#2 BASIC NEURAL NETWORK WITH MULTIPLE 2 HIDDEN LAYERS AND SIGMOID FUNCTION

In [55]:
x = np.concatenate((x_train, x_test))
y = np.concatenate((y_train, y_test))

In [56]:
# Split the data into training and testing sets
num_train = int(0.69 * len(x))
x_train, y_train = x[:num_train], y[:num_train]
x_test, y_test = x[num_train:], y[num_train:]

# Reshape the input data to be 2D (samples x features)
x_train_flattened = x_train.reshape(-1, 784)
x_test_flattened = x_test.reshape(-1, 784)


In [14]:
model = keras.Sequential([
    keras.layers.Dense(150, input_shape = (784,),activation = 'sigmoid') ,
    keras.layers.Dense(150, input_shape = (784,),activation = 'sigmoid') ,
    keras.layers.Dense(10 ,activation = 'softmax')

])

model.compile(optimizer = 'adam' ,
              loss =  'sparse_categorical_crossentropy' ,
              metrics = ['accuracy'])

model.fit(x_train_flattened, y_train, epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 13s 6ms/step - loss: 0.4090 - accuracy: 0.8878
Epoch 2/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.1679 - accuracy: 0.9509
Epoch 3/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1147 - accuracy: 0.9661
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0840 - accuracy: 0.9744
Epoch 5/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0642 - accuracy: 0.9803


In [15]:
model.evaluate(x_test_flattened, y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.0874 - accuracy: 0.9721


[0.08736637234687805, 0.972100019454956]

In [51]:
y_predicted2 = model.predict(x_test_flattened)
y_predicted_labels2 = [np.argmax(i) for i in y_predicted1]

700/700 [==============================] - 2s 2ms/step


In [ ]:
# confusion_matrix2 = tf.math.confusion_matrix(labels = y_test,predictions = y_predicted_labels2 )
# confusion_matrix2
num_classes = 10
confusion_matrix2 = np.zeros((num_classes, num_classes))
for i in range(len(y_test)):
    true_label2 = y_test[i]
    predicted_label2 = y_predicted_labels2[i]
    confusion_matrix[true_label2][predicted_label2] += 1

print(confusion_matrix2)


#3 BASIC NEURAL NETWORK WITH MULTIPLE 2 HIDDEN LAYERS AND TANH FUNCTION

In [18]:
model = keras.Sequential([
    keras.layers.Dense(100, input_shape = (784,),activation = 'tanh') ,
    keras.layers.Dense(100, input_shape = (784,),activation = 'tanh') ,
    keras.layers.Dense(10 ,activation = 'softmax')

])

model.compile(optimizer = 'adam' ,
              loss =  'sparse_categorical_crossentropy' ,
              metrics = ['accuracy'])

model.fit(x_train_flattened, y_train, epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.2626 - accuracy: 0.9224
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1195 - accuracy: 0.9636
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0807 - accuracy: 0.9746
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0619 - accuracy: 0.9802
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0465 - accuracy: 0.9850


In [19]:
model.evaluate(x_test_flattened, y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.0927 - accuracy: 0.9714


[0.0927216038107872, 0.9714000225067139]

In [20]:
confusion_matrix = tf.math.confusion_matrix(labels = y_test,predictions = y_predicted_labels )
confusion_matrix

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 965,    0,    1,    2,    0,    4,    5,    2,    1,    0],
       [   0, 1116,    3,    2,    0,    1,    4,    2,    7,    0],
       [   9,    7,  936,   13,    8,    1,   12,    9,   33,    4],
       [   5,    0,   27,  915,    0,   22,    3,    9,   21,    8],
       [   2,    1,    6,    1,  919,    0,    9,    4,    7,   33],
       [  10,    3,    5,   36,   12,  755,   17,    7,   38,    9],
       [  14,    3,    8,    1,    7,    8,  914,    2,    1,    0],
       [   1,    5,   27,    5,   10,    0,    0,  944,    2,   34],
       [   8,   10,    9,   20,    9,   22,   10,   12,  866,    8],
       [  11,    7,    1,    9,   29,    6,    0,   22,    8,  916]],
      dtype=int32)>

#4 BASIC NEURAL NETWORK WITH MULTIPLE 2 HIDDEN LAYERS AND TANH FUNCTION

In [22]:
model = keras.Sequential([
    keras.layers.Dense(150, input_shape = (784,),activation = 'tanh') ,
    keras.layers.Dense(150, input_shape = (784,),activation = 'tanh') ,
    keras.layers.Dense(10 ,activation = 'softmax')

])

model.compile(optimizer = 'adam' ,
              loss =  'sparse_categorical_crossentropy' ,
              metrics = ['accuracy'])

model.fit(x_train_flattened, y_train, epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.2545 - accuracy: 0.9243
Epoch 2/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1151 - accuracy: 0.9650
Epoch 3/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0786 - accuracy: 0.9749
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0569 - accuracy: 0.9823
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0426 - accuracy: 0.9869


In [23]:
model.evaluate(x_test_flattened, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.0817 - accuracy: 0.9727


[0.08167914301156998, 0.9726999998092651]

In [24]:
confusion_matrix = tf.math.confusion_matrix(labels = y_test,predictions = y_predicted_labels )
confusion_matrix

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 965,    0,    1,    2,    0,    4,    5,    2,    1,    0],
       [   0, 1116,    3,    2,    0,    1,    4,    2,    7,    0],
       [   9,    7,  936,   13,    8,    1,   12,    9,   33,    4],
       [   5,    0,   27,  915,    0,   22,    3,    9,   21,    8],
       [   2,    1,    6,    1,  919,    0,    9,    4,    7,   33],
       [  10,    3,    5,   36,   12,  755,   17,    7,   38,    9],
       [  14,    3,    8,    1,    7,    8,  914,    2,    1,    0],
       [   1,    5,   27,    5,   10,    0,    0,  944,    2,   34],
       [   8,   10,    9,   20,    9,   22,   10,   12,  866,    8],
       [  11,    7,    1,    9,   29,    6,    0,   22,    8,  916]],
      dtype=int32)>

#5 BASIC NEURAL NETWORK WITH MULTIPLE 2 HIDDEN LAYERS AND RELU FUNCTION

In [25]:
model = keras.Sequential([
    keras.layers.Dense(100, input_shape = (784,),activation = 'relu') ,
    keras.layers.Dense(100, input_shape = (784,),activation = 'relu') ,
    keras.layers.Dense(10 ,activation = 'softmax')

])

model.compile(optimizer = 'adam' ,
              loss =  'sparse_categorical_crossentropy' ,
              metrics = ['accuracy'])

model.fit(x_train_flattened, y_train, epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2436 - accuracy: 0.9280
Epoch 2/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1040 - accuracy: 0.9684
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0754 - accuracy: 0.9764
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0562 - accuracy: 0.9826
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0444 - accuracy: 0.9857


In [26]:
model.evaluate(x_test_flattened, y_test)

Exception ignored in: <function _xla_gc_callback at 0x7fa5f373d1f0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/jax/_src/lib/__init__.py", line 97, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt: 


313/313 [==============================] - 61s 2ms/step - loss: 0.0815 - accuracy: 0.9751


[0.08149614930152893, 0.9750999808311462]

In [27]:
confusion_matrix = tf.math.confusion_matrix(labels = y_test,predictions = y_predicted_labels )
confusion_matrix

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 965,    0,    1,    2,    0,    4,    5,    2,    1,    0],
       [   0, 1116,    3,    2,    0,    1,    4,    2,    7,    0],
       [   9,    7,  936,   13,    8,    1,   12,    9,   33,    4],
       [   5,    0,   27,  915,    0,   22,    3,    9,   21,    8],
       [   2,    1,    6,    1,  919,    0,    9,    4,    7,   33],
       [  10,    3,    5,   36,   12,  755,   17,    7,   38,    9],
       [  14,    3,    8,    1,    7,    8,  914,    2,    1,    0],
       [   1,    5,   27,    5,   10,    0,    0,  944,    2,   34],
       [   8,   10,    9,   20,    9,   22,   10,   12,  866,    8],
       [  11,    7,    1,    9,   29,    6,    0,   22,    8,  916]],
      dtype=int32)>

#6 BASIC NEURAL NETWORK WITH MULTIPLE 2 HIDDEN LAYERS AND RELU FUNCTION

In [28]:
model = keras.Sequential([
    keras.layers.Dense(150, input_shape = (784,),activation = 'relu') ,
    keras.layers.Dense(150, input_shape = (784,),activation = 'relu') ,
    keras.layers.Dense(10 ,activation = 'softmax')

])

model.compile(optimizer = 'adam' ,
              loss =  'sparse_categorical_crossentropy' ,
              metrics = ['accuracy'])

model.fit(x_train_flattened, y_train, epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.2198 - accuracy: 0.9347
Epoch 2/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0920 - accuracy: 0.9718
Epoch 3/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0652 - accuracy: 0.9800
Epoch 4/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0478 - accuracy: 0.9843
Epoch 5/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0396 - accuracy: 0.9873


In [29]:
model.evaluate(x_test_flattened, y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.0879 - accuracy: 0.9726


[0.0878523513674736, 0.972599983215332]

In [30]:
confusion_matrix = tf.math.confusion_matrix(labels = y_test,predictions = y_predicted_labels )
confusion_matrix

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 965,    0,    1,    2,    0,    4,    5,    2,    1,    0],
       [   0, 1116,    3,    2,    0,    1,    4,    2,    7,    0],
       [   9,    7,  936,   13,    8,    1,   12,    9,   33,    4],
       [   5,    0,   27,  915,    0,   22,    3,    9,   21,    8],
       [   2,    1,    6,    1,  919,    0,    9,    4,    7,   33],
       [  10,    3,    5,   36,   12,  755,   17,    7,   38,    9],
       [  14,    3,    8,    1,    7,    8,  914,    2,    1,    0],
       [   1,    5,   27,    5,   10,    0,    0,  944,    2,   34],
       [   8,   10,    9,   20,    9,   22,   10,   12,  866,    8],
       [  11,    7,    1,    9,   29,    6,    0,   22,    8,  916]],
      dtype=int32)>

#7 BASIC NEURAL NETWORK WITH MULTIPLE 3 HIDDEN LAYERS AND SIGMOID FUNCTION

In [32]:
model = keras.Sequential([
    keras.layers.Dense(100, input_shape = (784,),activation = 'sigmoid') ,
    keras.layers.Dense(100, input_shape = (784,),activation = 'sigmoid') ,
    keras.layers.Dense(100, input_shape = (784,),activation = 'sigmoid') ,
    keras.layers.Dense(10 ,activation = 'softmax')

])

model.compile(optimizer = 'adam' ,
              loss =  'sparse_categorical_crossentropy' ,
              metrics = ['accuracy'])

model.fit(x_train_flattened, y_train, epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.5194 - accuracy: 0.8519
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1769 - accuracy: 0.9475
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1207 - accuracy: 0.9645
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0913 - accuracy: 0.9731
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0725 - accuracy: 0.9788


In [35]:
model.evaluate(x_test_flattened, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.0940 - accuracy: 0.9723


[0.09402132779359818, 0.9722999930381775]

In [36]:
confusion_matrix = tf.math.confusion_matrix(labels = y_test,predictions = y_predicted_labels )
confusion_matrix

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 965,    0,    1,    2,    0,    4,    5,    2,    1,    0],
       [   0, 1116,    3,    2,    0,    1,    4,    2,    7,    0],
       [   9,    7,  936,   13,    8,    1,   12,    9,   33,    4],
       [   5,    0,   27,  915,    0,   22,    3,    9,   21,    8],
       [   2,    1,    6,    1,  919,    0,    9,    4,    7,   33],
       [  10,    3,    5,   36,   12,  755,   17,    7,   38,    9],
       [  14,    3,    8,    1,    7,    8,  914,    2,    1,    0],
       [   1,    5,   27,    5,   10,    0,    0,  944,    2,   34],
       [   8,   10,    9,   20,    9,   22,   10,   12,  866,    8],
       [  11,    7,    1,    9,   29,    6,    0,   22,    8,  916]],
      dtype=int32)>

#8 BASIC NEURAL NETWORK WITH MULTIPLE 3 HIDDEN LAYERS AND SIGMOID FUNCTION

In [31]:
model = keras.Sequential([
    keras.layers.Dense(150, input_shape = (784,),activation = 'sigmoid') ,
    keras.layers.Dense(150, input_shape = (784,),activation = 'sigmoid') ,
    keras.layers.Dense(150, input_shape = (784,),activation = 'sigmoid') ,
    keras.layers.Dense(10 ,activation = 'softmax')

])

model.compile(optimizer = 'adam' ,
              loss =  'sparse_categorical_crossentropy' ,
              metrics = ['accuracy'])

model.fit(x_train_flattened, y_train, epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 11s 5ms/step - loss: 0.4511 - accuracy: 0.8657
Epoch 2/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.1566 - accuracy: 0.9522
Epoch 3/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.1088 - accuracy: 0.9670
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0804 - accuracy: 0.9755
Epoch 5/5
1875/1875 [==============================] - 10s 6ms/step - loss: 0.0633 - accuracy: 0.9803


In [33]:
model.evaluate(x_test_flattened, y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.0940 - accuracy: 0.9723


[0.09402132779359818, 0.9722999930381775]

In [34]:
confusion_matrix = tf.math.confusion_matrix(labels = y_test,predictions = y_predicted_labels )
confusion_matrix

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 965,    0,    1,    2,    0,    4,    5,    2,    1,    0],
       [   0, 1116,    3,    2,    0,    1,    4,    2,    7,    0],
       [   9,    7,  936,   13,    8,    1,   12,    9,   33,    4],
       [   5,    0,   27,  915,    0,   22,    3,    9,   21,    8],
       [   2,    1,    6,    1,  919,    0,    9,    4,    7,   33],
       [  10,    3,    5,   36,   12,  755,   17,    7,   38,    9],
       [  14,    3,    8,    1,    7,    8,  914,    2,    1,    0],
       [   1,    5,   27,    5,   10,    0,    0,  944,    2,   34],
       [   8,   10,    9,   20,    9,   22,   10,   12,  866,    8],
       [  11,    7,    1,    9,   29,    6,    0,   22,    8,  916]],
      dtype=int32)>

#9 BASIC NEURAL NETWORK WITH MULTIPLE 3 HIDDEN LAYERS AND TANH FUNCTION




In [38]:
model = keras.Sequential([
    keras.layers.Dense(100, input_shape = (784,),activation = 'tanh') ,
    keras.layers.Dense(100, input_shape = (784,),activation = 'tanh') ,
    keras.layers.Dense(100, input_shape = (784,),activation = 'tanh') ,
    keras.layers.Dense(10 ,activation = 'softmax')

])

model.compile(optimizer = 'adam' ,
              loss =  'sparse_categorical_crossentropy' ,
              metrics = ['accuracy'])

model.fit(x_train_flattened, y_train, epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2547 - accuracy: 0.9246
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1187 - accuracy: 0.9642
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0847 - accuracy: 0.9736
Epoch 4/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0647 - accuracy: 0.9796
Epoch 5/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0514 - accuracy: 0.9833


In [39]:
model.evaluate(x_test_flattened, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.0921 - accuracy: 0.9726


[0.09210652112960815, 0.972599983215332]

In [40]:
confusion_matrix = tf.math.confusion_matrix(labels = y_test,predictions = y_predicted_labels )
confusion_matrix

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 965,    0,    1,    2,    0,    4,    5,    2,    1,    0],
       [   0, 1116,    3,    2,    0,    1,    4,    2,    7,    0],
       [   9,    7,  936,   13,    8,    1,   12,    9,   33,    4],
       [   5,    0,   27,  915,    0,   22,    3,    9,   21,    8],
       [   2,    1,    6,    1,  919,    0,    9,    4,    7,   33],
       [  10,    3,    5,   36,   12,  755,   17,    7,   38,    9],
       [  14,    3,    8,    1,    7,    8,  914,    2,    1,    0],
       [   1,    5,   27,    5,   10,    0,    0,  944,    2,   34],
       [   8,   10,    9,   20,    9,   22,   10,   12,  866,    8],
       [  11,    7,    1,    9,   29,    6,    0,   22,    8,  916]],
      dtype=int32)>

#10 BASIC NEURAL NETWORK WITH MULTIPLE 3 HIDDEN LAYERS AND TANH FUNCTION




In [41]:
model = keras.Sequential([
    keras.layers.Dense(150, input_shape = (784,),activation = 'tanh') ,
    keras.layers.Dense(150, input_shape = (784,),activation = 'tanh') ,
    keras.layers.Dense(150, input_shape = (784,),activation = 'tanh') ,
    keras.layers.Dense(10 ,activation = 'softmax')

])

model.compile(optimizer = 'adam' ,
              loss =  'sparse_categorical_crossentropy' ,
              metrics = ['accuracy'])

model.fit(x_train_flattened, y_train, epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 13s 6ms/step - loss: 0.2471 - accuracy: 0.9246
Epoch 2/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.1184 - accuracy: 0.9639
Epoch 3/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0799 - accuracy: 0.9748
Epoch 4/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0600 - accuracy: 0.9812
Epoch 5/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0462 - accuracy: 0.9852


In [42]:
model.evaluate(x_test_flattened, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.0879 - accuracy: 0.9750


[0.08794111013412476, 0.9750000238418579]

In [43]:
confusion_matrix = tf.math.confusion_matrix(labels = y_test,predictions = y_predicted_labels )
confusion_matrix

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 965,    0,    1,    2,    0,    4,    5,    2,    1,    0],
       [   0, 1116,    3,    2,    0,    1,    4,    2,    7,    0],
       [   9,    7,  936,   13,    8,    1,   12,    9,   33,    4],
       [   5,    0,   27,  915,    0,   22,    3,    9,   21,    8],
       [   2,    1,    6,    1,  919,    0,    9,    4,    7,   33],
       [  10,    3,    5,   36,   12,  755,   17,    7,   38,    9],
       [  14,    3,    8,    1,    7,    8,  914,    2,    1,    0],
       [   1,    5,   27,    5,   10,    0,    0,  944,    2,   34],
       [   8,   10,    9,   20,    9,   22,   10,   12,  866,    8],
       [  11,    7,    1,    9,   29,    6,    0,   22,    8,  916]],
      dtype=int32)>

#11 BASIC NEURAL NETWORK WITH MULTIPLE 3 HIDDEN LAYERS AND RELU FUNCTION




In [44]:
model = keras.Sequential([
    keras.layers.Dense(100, input_shape = (784,),activation = 'relu') ,
    keras.layers.Dense(100, input_shape = (784,),activation = 'relu') ,
    keras.layers.Dense(100, input_shape = (784,),activation = 'relu') ,

    keras.layers.Dense(10 ,activation = 'softmax')

])

model.compile(optimizer = 'adam' ,
              loss =  'sparse_categorical_crossentropy' ,
              metrics = ['accuracy'])

model.fit(x_train_flattened, y_train, epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2422 - accuracy: 0.9286
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1065 - accuracy: 0.9675
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0778 - accuracy: 0.9758
Epoch 4/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.0614 - accuracy: 0.9799
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0481 - accuracy: 0.9844


In [45]:
model.evaluate(x_test_flattened, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.1019 - accuracy: 0.9714


[0.1019347608089447, 0.9714000225067139]

In [46]:
confusion_matrix = tf.math.confusion_matrix(labels = y_test,predictions = y_predicted_labels )
confusion_matrix

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 965,    0,    1,    2,    0,    4,    5,    2,    1,    0],
       [   0, 1116,    3,    2,    0,    1,    4,    2,    7,    0],
       [   9,    7,  936,   13,    8,    1,   12,    9,   33,    4],
       [   5,    0,   27,  915,    0,   22,    3,    9,   21,    8],
       [   2,    1,    6,    1,  919,    0,    9,    4,    7,   33],
       [  10,    3,    5,   36,   12,  755,   17,    7,   38,    9],
       [  14,    3,    8,    1,    7,    8,  914,    2,    1,    0],
       [   1,    5,   27,    5,   10,    0,    0,  944,    2,   34],
       [   8,   10,    9,   20,    9,   22,   10,   12,  866,    8],
       [  11,    7,    1,    9,   29,    6,    0,   22,    8,  916]],
      dtype=int32)>

#12 BASIC NEURAL NETWORK WITH MULTIPLE 3 HIDDEN LAYERS AND RELU FUNCTION




In [47]:
model = keras.Sequential([
    keras.layers.Dense(150, input_shape = (784,),activation = 'relu') ,
    keras.layers.Dense(150, input_shape = (784,),activation = 'relu') ,
    keras.layers.Dense(150, input_shape = (784,),activation = 'relu') ,

    keras.layers.Dense(10 ,activation = 'softmax')

])

model.compile(optimizer = 'adam' ,
              loss =  'sparse_categorical_crossentropy' ,
              metrics = ['accuracy'])

model.fit(x_train_flattened, y_train, epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.2252 - accuracy: 0.9323
Epoch 2/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0987 - accuracy: 0.9696
Epoch 3/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0704 - accuracy: 0.9772
Epoch 4/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0558 - accuracy: 0.9820
Epoch 5/5
1875/1875 [==============================] - 10s 6ms/step - loss: 0.0456 - accuracy: 0.9859


In [48]:
model.evaluate(x_test_flattened, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.0816 - accuracy: 0.9768


[0.08157890290021896, 0.9768000245094299]

In [49]:
confusion_matrix = tf.math.confusion_matrix(labels = y_test,predictions = y_predicted_labels )
confusion_matrix

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 965,    0,    1,    2,    0,    4,    5,    2,    1,    0],
       [   0, 1116,    3,    2,    0,    1,    4,    2,    7,    0],
       [   9,    7,  936,   13,    8,    1,   12,    9,   33,    4],
       [   5,    0,   27,  915,    0,   22,    3,    9,   21,    8],
       [   2,    1,    6,    1,  919,    0,    9,    4,    7,   33],
       [  10,    3,    5,   36,   12,  755,   17,    7,   38,    9],
       [  14,    3,    8,    1,    7,    8,  914,    2,    1,    0],
       [   1,    5,   27,    5,   10,    0,    0,  944,    2,   34],
       [   8,   10,    9,   20,    9,   22,   10,   12,  866,    8],
       [  11,    7,    1,    9,   29,    6,    0,   22,    8,  916]],
      dtype=int32)>